// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Project1

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainScreen
extern void ui_MainScreen_screen_init(void);
extern void ui_MainScreen_screen_destroy(void);
extern lv_obj_t *ui_MainScreen;
extern lv_obj_t *ui_centerCircle;
extern lv_obj_t *ui_imgStart;
extern lv_obj_t *ui_imgGo;
extern lv_obj_t *ui_Spinner1;
extern lv_obj_t *ui_player1;
extern lv_obj_t *ui_player2;
extern lv_obj_t *ui_player3;
extern lv_obj_t *ui_player4;
extern lv_obj_t *ui_player1Ready;
extern lv_obj_t *ui_player2Ready;
extern lv_obj_t *ui_player3Ready;
extern lv_obj_t *ui_player4Ready;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

