// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Project1

#include "../ui.h"

lv_obj_t *ui_MainScreen = NULL;lv_obj_t *ui_centerCircle = NULL;lv_obj_t *ui_imgStart = NULL;lv_obj_t *ui_imgGo = NULL;lv_obj_t *ui_Spinner1 = NULL;lv_obj_t *ui_player1 = NULL;lv_obj_t *ui_player2 = NULL;lv_obj_t *ui_player3 = NULL;lv_obj_t *ui_player4 = NULL;lv_obj_t *ui_player1Ready = NULL;lv_obj_t *ui_player2Ready = NULL;lv_obj_t *ui_player3Ready = NULL;lv_obj_t *ui_player4Ready = NULL;
// event funtions

// build funtions

void ui_MainScreen_screen_init(void)
{
ui_MainScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_centerCircle = lv_img_create(ui_MainScreen);
lv_img_set_src(ui_centerCircle, &ui_img_img_ellipse_1_png);
lv_obj_set_width( ui_centerCircle, LV_SIZE_CONTENT);  /// 320
lv_obj_set_height( ui_centerCircle, LV_SIZE_CONTENT);   /// 320
lv_obj_set_x( ui_centerCircle, 12 );
lv_obj_set_y( ui_centerCircle, 72 );
lv_obj_set_align( ui_centerCircle, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_centerCircle, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_centerCircle, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_imgStart = lv_img_create(ui_MainScreen);
lv_img_set_src(ui_imgStart, &ui_img_img_start_png);
lv_obj_set_width( ui_imgStart, LV_SIZE_CONTENT);  /// 274
lv_obj_set_height( ui_imgStart, LV_SIZE_CONTENT);   /// 64
lv_obj_set_x( ui_imgStart, 14 );
lv_obj_set_y( ui_imgStart, 70 );
lv_obj_set_align( ui_imgStart, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_imgStart, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_imgStart, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_imgGo = lv_img_create(ui_MainScreen);
lv_img_set_src(ui_imgGo, &ui_img_725341252);
lv_obj_set_width( ui_imgGo, LV_SIZE_CONTENT);  /// 143
lv_obj_set_height( ui_imgGo, LV_SIZE_CONTENT);   /// 64
lv_obj_set_x( ui_imgGo, 11 );
lv_obj_set_y( ui_imgGo, 72 );
lv_obj_set_align( ui_imgGo, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_imgGo, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_imgGo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Spinner1 = lv_spinner_create(ui_MainScreen,1000,90);
lv_obj_set_width( ui_Spinner1, 417);
lv_obj_set_height( ui_Spinner1, 322);
lv_obj_set_x( ui_Spinner1, 60 );
lv_obj_set_y( ui_Spinner1, 72 );
lv_obj_set_align( ui_Spinner1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Spinner1, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_Spinner1, LV_OBJ_FLAG_CLICKABLE );    /// Flags

ui_player1 = lv_img_create(ui_MainScreen);
lv_img_set_src(ui_player1, &ui_img_img_player1_png);
lv_obj_set_width( ui_player1, LV_SIZE_CONTENT);  /// 150
lv_obj_set_height( ui_player1, LV_SIZE_CONTENT);   /// 150
lv_obj_set_x( ui_player1, -293 );
lv_obj_set_y( ui_player1, -152 );
lv_obj_set_align( ui_player1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_player1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_player1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_player2 = lv_img_create(ui_MainScreen);
lv_img_set_src(ui_player2, &ui_img_img_player2_png);
lv_obj_set_width( ui_player2, LV_SIZE_CONTENT);  /// 150
lv_obj_set_height( ui_player2, LV_SIZE_CONTENT);   /// 150
lv_obj_set_x( ui_player2, -90 );
lv_obj_set_y( ui_player2, -152 );
lv_obj_set_align( ui_player2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_player2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_player2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_player3 = lv_img_create(ui_MainScreen);
lv_img_set_src(ui_player3, &ui_img_img_player3_png);
lv_obj_set_width( ui_player3, LV_SIZE_CONTENT);  /// 150
lv_obj_set_height( ui_player3, LV_SIZE_CONTENT);   /// 150
lv_obj_set_x( ui_player3, 104 );
lv_obj_set_y( ui_player3, -152 );
lv_obj_set_align( ui_player3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_player3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_player3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_player4 = lv_img_create(ui_MainScreen);
lv_img_set_src(ui_player4, &ui_img_img_player4_png);
lv_obj_set_width( ui_player4, LV_SIZE_CONTENT);  /// 150
lv_obj_set_height( ui_player4, LV_SIZE_CONTENT);   /// 150
lv_obj_set_x( ui_player4, 296 );
lv_obj_set_y( ui_player4, -152 );
lv_obj_set_align( ui_player4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_player4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_player4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_player1Ready = lv_img_create(ui_MainScreen);
lv_img_set_src(ui_player1Ready, &ui_img_img_ellipse_10_png);
lv_obj_set_width( ui_player1Ready, LV_SIZE_CONTENT);  /// 150
lv_obj_set_height( ui_player1Ready, LV_SIZE_CONTENT);   /// 150
lv_obj_set_x( ui_player1Ready, -293 );
lv_obj_set_y( ui_player1Ready, -152 );
lv_obj_set_align( ui_player1Ready, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_player1Ready,  LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_player1Ready, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_player2Ready = lv_img_create(ui_MainScreen);
lv_img_set_src(ui_player2Ready, &ui_img_img_ellipse_10_png);
lv_obj_set_width( ui_player2Ready, LV_SIZE_CONTENT);  /// 150
lv_obj_set_height( ui_player2Ready, LV_SIZE_CONTENT);   /// 150
lv_obj_set_x( ui_player2Ready, -90 );
lv_obj_set_y( ui_player2Ready, -152 );
lv_obj_set_align( ui_player2Ready, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_player2Ready, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_player2Ready, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_player3Ready = lv_img_create(ui_MainScreen);
lv_img_set_src(ui_player3Ready, &ui_img_img_ellipse_10_png);
lv_obj_set_width( ui_player3Ready, LV_SIZE_CONTENT);  /// 150
lv_obj_set_height( ui_player3Ready, LV_SIZE_CONTENT);   /// 150
lv_obj_set_x( ui_player3Ready, 104 );
lv_obj_set_y( ui_player3Ready, -152 );
lv_obj_set_align( ui_player3Ready, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_player3Ready, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_player3Ready, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_player4Ready = lv_img_create(ui_MainScreen);
lv_img_set_src(ui_player4Ready, &ui_img_img_ellipse_10_png);
lv_obj_set_width( ui_player4Ready, LV_SIZE_CONTENT);  /// 150
lv_obj_set_height( ui_player4Ready, LV_SIZE_CONTENT);   /// 150
lv_obj_set_x( ui_player4Ready, 296 );
lv_obj_set_y( ui_player4Ready, -152 );
lv_obj_set_align( ui_player4Ready, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_player4Ready, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_player4Ready, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}

void ui_MainScreen_screen_destroy(void)
{
   if (ui_MainScreen) lv_obj_del(ui_MainScreen);

// NULL screen variables
ui_MainScreen= NULL;
ui_centerCircle= NULL;
ui_imgStart= NULL;
ui_imgGo= NULL;
ui_Spinner1= NULL;
ui_player1= NULL;
ui_player2= NULL;
ui_player3= NULL;
ui_player4= NULL;
ui_player1Ready= NULL;
ui_player2Ready= NULL;
ui_player3Ready= NULL;
ui_player4Ready= NULL;

}
